# Generated by Django 3.1.4 on 2021-02-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210203_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagealbum',
            options={'verbose_name': 'ImageAlbum'},
        ),
    ]
