# Generated by Django 3.1.4 on 2021-02-06 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('product', '0005_auto_20210203_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.brand', verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop_product',
            field=models.ManyToManyField(related_name='products', through='product.ShopProduct', to='account.Shop'),
        ),
    ]
