# Generated by Django 3.1.4 on 2021-02-12 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210211_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmeta',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', related_query_name='metas', to='product.product'),
        ),
    ]
