# Generated by Django 3.1.4 on 2021-02-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_shopproductmeta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopProductMeta',
        ),
    ]
