# Generated by Django 3.1.4 on 2021-01-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('sub_title', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='media/slideshow/')),
                ('action_text', models.CharField(default='shop now', max_length=20)),
                ('action_url', models.URLField(default='http://127.0.0.1:8000')),
            ],
        ),
    ]
