# Generated by Django 3.1.4 on 2021-02-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
